import type {
  BacktestResult,
  DailyReport,
  IndexDatum,
  MarketMover,
  MarketOverview,
  SectorRanking,
  StockWatchItem,
  TradeJournal,
} from "@/lib/types";

export const riskDisclaimer =
  "本系统仅用于投资研究、量化分析和交易复盘，不构成任何投资建议。股市有风险，交易需谨慎。所有买卖决策由用户自行承担。";

export const indexData: IndexDatum[] = [
  {
    name: "上证指数",
    code: "000001.SH",
    value: "3,612.48",
    changePercent: "+0.42%",
    changePoints: "+15.08",
    trend: "up",
    series: [
      { time: "09:30", value: 3592 },
      { time: "10:00", value: 3598 },
      { time: "10:30", value: 3604 },
      { time: "11:00", value: 3601 },
      { time: "13:00", value: 3609 },
      { time: "13:30", value: 3615 },
      { time: "14:00", value: 3611 },
      { time: "14:30", value: 3617 },
      { time: "15:00", value: 3612 },
    ],
  },
  {
    name: "深证成指",
    code: "399001.SZ",
    value: "11,248.73",
    changePercent: "-0.18%",
    changePoints: "-20.31",
    trend: "down",
    series: [
      { time: "09:30", value: 11268 },
      { time: "10:00", value: 11291 },
      { time: "10:30", value: 11274 },
      { time: "11:00", value: 11233 },
      { time: "13:00", value: 11220 },
      { time: "13:30", value: 11245 },
      { time: "14:00", value: 11231 },
      { time: "14:30", value: 11261 },
      { time: "15:00", value: 11249 },
    ],
  },
  {
    name: "创业板指",
    code: "399006.SZ",
    value: "2,314.66",
    changePercent: "+0.86%",
    changePoints: "+19.72",
    trend: "up",
    series: [
      { time: "09:30", value: 2292 },
      { time: "10:00", value: 2298 },
      { time: "10:30", value: 2306 },
      { time: "11:00", value: 2303 },
      { time: "13:00", value: 2311 },
      { time: "13:30", value: 2319 },
      { time: "14:00", value: 2316 },
      { time: "14:30", value: 2321 },
      { time: "15:00", value: 2315 },
    ],
  },
];

export const marketOverview: MarketOverview = {
  breadth: {
    rising: 3186,
    falling: 1842,
    unchanged: 216,
    limitUp: 68,
    limitDown: 14,
  },
  turnover: {
    total: "9,652 亿",
    sh: "4,106 亿",
    sz: "5,546 亿",
    change: "+8.7%",
  },
  sentiment: {
    score: 64,
    label: "中性偏暖",
    description: "热点延续但分化明显，适合观察资金承接，不适合追高。",
  },
  riskLevel: "中性偏谨慎",
};

export const intradayMarketFlow = [
  { time: "09:30", amount: 512, sentiment: 48 },
  { time: "10:00", amount: 1180, sentiment: 56 },
  { time: "10:30", amount: 2146, sentiment: 61 },
  { time: "11:00", amount: 3298, sentiment: 58 },
  { time: "13:00", amount: 5180, sentiment: 64 },
  { time: "13:30", amount: 6320, sentiment: 67 },
  { time: "14:00", amount: 7416, sentiment: 63 },
  { time: "14:30", amount: 8678, sentiment: 59 },
  { time: "15:00", amount: 9652, sentiment: 62 },
];

export const marketMovers = {
  gainers: [
    {
      code: "688256",
      name: "寒武纪",
      sector: "算力基础设施",
      price: "628.40",
      changePercent: "+8.92%",
      turnover: "112 亿",
      reason: "算力链情绪升温",
    },
    {
      code: "300308",
      name: "中际旭创",
      sector: "光模块",
      price: "184.22",
      changePercent: "+7.36%",
      turnover: "96 亿",
      reason: "成交持续放大",
    },
    {
      code: "002371",
      name: "北方华创",
      sector: "半导体设备",
      price: "418.10",
      changePercent: "+6.48%",
      turnover: "74 亿",
      reason: "板块强度领先",
    },
    {
      code: "300124",
      name: "汇川技术",
      sector: "机器人",
      price: "72.56",
      changePercent: "+5.91%",
      turnover: "43 亿",
      reason: "机构资金回流",
    },
  ] satisfies MarketMover[],
  losers: [
    {
      code: "601899",
      name: "紫金矿业",
      sector: "有色金属",
      price: "18.72",
      changePercent: "-4.81%",
      turnover: "58 亿",
      reason: "资源股回撤",
    },
    {
      code: "600809",
      name: "山西汾酒",
      sector: "白酒",
      price: "246.30",
      changePercent: "-3.94%",
      turnover: "36 亿",
      reason: "消费权重承压",
    },
    {
      code: "601318",
      name: "中国平安",
      sector: "保险",
      price: "47.18",
      changePercent: "-2.76%",
      turnover: "41 亿",
      reason: "金融权重调整",
    },
    {
      code: "600031",
      name: "三一重工",
      sector: "工程机械",
      price: "17.42",
      changePercent: "-2.18%",
      turnover: "23 亿",
      reason: "周期风格降温",
    },
  ] satisfies MarketMover[],
  turnoverLeaders: [
    {
      code: "300750",
      name: "宁德时代",
      sector: "新能源",
      price: "236.18",
      changePercent: "+1.44%",
      turnover: "138 亿",
      reason: "权重成交活跃",
    },
    {
      code: "600519",
      name: "贵州茅台",
      sector: "白酒",
      price: "1,692.00",
      changePercent: "-0.62%",
      turnover: "121 亿",
      reason: "大盘风险偏好锚点",
    },
    {
      code: "688256",
      name: "寒武纪",
      sector: "算力基础设施",
      price: "628.40",
      changePercent: "+8.92%",
      turnover: "112 亿",
      reason: "高弹性核心标的",
    },
    {
      code: "300308",
      name: "中际旭创",
      sector: "光模块",
      price: "184.22",
      changePercent: "+7.36%",
      turnover: "96 亿",
      reason: "资金承接较强",
    },
  ] satisfies MarketMover[],
};

export const sectorRankings: SectorRanking[] = [
  {
    rank: 1,
    name: "半导体设备",
    changePercent: "+3.42%",
    turnover: "812 亿",
    heat: 92,
    limitUp: 9,
    leader: "北方华创",
    riskLevel: "中",
    focus: "适合关注",
    rotation: "强势延续，关注分歧后的承接。",
  },
  {
    rank: 2,
    name: "算力基础设施",
    changePercent: "+2.86%",
    turnover: "694 亿",
    heat: 88,
    limitUp: 7,
    leader: "寒武纪",
    riskLevel: "中",
    focus: "适合关注",
    rotation: "成交活跃，但短线拥挤度抬升。",
  },
  {
    rank: 3,
    name: "低空经济",
    changePercent: "+2.15%",
    turnover: "488 亿",
    heat: 81,
    limitUp: 6,
    leader: "万丰奥威",
    riskLevel: "高",
    focus: "谨慎观察",
    rotation: "主题波动偏大，等待回踩确认。",
  },
  {
    rank: 4,
    name: "机器人",
    changePercent: "+1.74%",
    turnover: "426 亿",
    heat: 76,
    limitUp: 5,
    leader: "汇川技术",
    riskLevel: "中",
    focus: "适合关注",
    rotation: "趋势修复，适合跟踪中军强弱。",
  },
  {
    rank: 5,
    name: "创新药",
    changePercent: "+1.29%",
    turnover: "391 亿",
    heat: 71,
    limitUp: 3,
    leader: "恒瑞医药",
    riskLevel: "中",
    focus: "谨慎观察",
    rotation: "防守与成长切换，关注持续性。",
  },
  {
    rank: 6,
    name: "地产链",
    changePercent: "-1.08%",
    turnover: "286 亿",
    heat: 34,
    limitUp: 1,
    leader: "保利发展",
    riskLevel: "高",
    focus: "暂不关注",
    rotation: "政策预期弱化，短线避开下行趋势。",
  },
];

export const sectorDirections = {
  strong: ["半导体设备", "算力基础设施", "机器人"],
  cautious: ["低空经济", "创新药", "新能源"],
  avoid: ["地产链", "弱周期资源", "高位缩量题材"],
};

export const stockWatchlist: StockWatchItem[] = [
  {
    code: "688981",
    name: "中芯国际",
    sector: "半导体设备",
    latestPrice: "92.48",
    changePercent: "+3.28%",
    score: 86,
    rating: "强观察",
    buyTrigger: "放量突破 94.20 且板块热度维持前三",
    stopLoss: "88.60",
    takeProfit: "99.80 - 103.50",
    risk: "消息面敏感，需控制追高风险",
  },
  {
    code: "002371",
    name: "北方华创",
    sector: "半导体设备",
    latestPrice: "418.10",
    changePercent: "+6.48%",
    score: 90,
    rating: "强观察",
    buyTrigger: "回踩 5 日线不破并再次放量",
    stopLoss: "396.00",
    takeProfit: "438.00 - 456.00",
    risk: "短线涨幅较大，分歧时波动放大",
  },
  {
    code: "300750",
    name: "宁德时代",
    sector: "新能源",
    latestPrice: "236.18",
    changePercent: "+1.44%",
    score: 74,
    rating: "谨慎观察",
    buyTrigger: "成交额维持前列且突破 240.00",
    stopLoss: "226.50",
    takeProfit: "248.00 - 255.00",
    risk: "新能源板块轮动速度快",
  },
  {
    code: "000977",
    name: "浪潮信息",
    sector: "算力基础设施",
    latestPrice: "58.36",
    changePercent: "+2.22%",
    score: 81,
    rating: "强观察",
    buyTrigger: "突破 59.20 且量能温和放大",
    stopLoss: "55.80",
    takeProfit: "62.50 - 65.00",
    risk: "算力主题拥挤度上升",
  },
  {
    code: "600519",
    name: "贵州茅台",
    sector: "白酒",
    latestPrice: "1,692.00",
    changePercent: "-0.62%",
    score: 58,
    rating: "暂不关注",
    buyTrigger: "重新站回 20 日线并放量修复",
    stopLoss: "1,650.00",
    takeProfit: "1,750.00 - 1,790.00",
    risk: "消费权重仍处于调整结构",
  },
  {
    code: "300308",
    name: "中际旭创",
    sector: "算力基础设施",
    latestPrice: "184.22",
    changePercent: "+7.36%",
    score: 84,
    rating: "谨慎观察",
    buyTrigger: "盘中分歧后不破 178.00",
    stopLoss: "172.60",
    takeProfit: "195.00 - 203.00",
    risk: "高位放量后可能剧烈震荡",
  },
];

export const backtestResult: BacktestResult = {
  strategyName: "热点板块突破观察策略",
  range: "2025-01-01 至 2025-12-31",
  universe: "沪深 A 股 mock 股票池",
  rules: [
    "热点板块排名前5",
    "股价站上5日线",
    "成交量温和放大",
    "RSI不过热",
    "次日突破买入",
  ],
  metrics: {
    totalReturn: "+18.6%",
    maxDrawdown: "-7.8%",
    winRate: "57.4%",
    profitLossRatio: "1.72",
    tradeCount: 46,
    averageHoldingDays: "5.8 天",
  },
  equityCurve: [
    { date: "01月", value: 1.0 },
    { date: "02月", value: 1.03 },
    { date: "03月", value: 1.08 },
    { date: "04月", value: 1.05 },
    { date: "05月", value: 1.12 },
    { date: "06月", value: 1.17 },
    { date: "07月", value: 1.14 },
    { date: "08月", value: 1.21 },
    { date: "09月", value: 1.19 },
    { date: "10月", value: 1.25 },
    { date: "11月", value: 1.23 },
    { date: "12月", value: 1.186 },
  ],
  trades: [
    {
      date: "2025-03-18",
      code: "688981",
      name: "中芯国际",
      action: "买入",
      price: "88.40",
      position: "15%",
      pnl: "+6.2%",
      note: "板块热度第一，突破前高",
    },
    {
      date: "2025-04-09",
      code: "000977",
      name: "浪潮信息",
      action: "卖出",
      price: "61.20",
      position: "12%",
      pnl: "+4.8%",
      note: "达到止盈区间，缩量兑现",
    },
    {
      date: "2025-06-14",
      code: "300750",
      name: "宁德时代",
      action: "买入",
      price: "228.60",
      position: "10%",
      pnl: "-2.6%",
      note: "新能源反弹失败，触发纪律止损",
    },
    {
      date: "2025-08-22",
      code: "002371",
      name: "北方华创",
      action: "卖出",
      price: "426.00",
      position: "15%",
      pnl: "+9.1%",
      note: "强趋势延续后出现分歧放量",
    },
  ],
};

export const tradeJournal: TradeJournal = {
  stats: {
    totalTrades: 38,
    winRate: "55.3%",
    totalReturn: "+12.4%",
    maxDrawdown: "-6.2%",
    currentPositions: 4,
  },
  pnlCurve: [
    { date: "01月", value: 0 },
    { date: "02月", value: 1.8 },
    { date: "03月", value: 4.4 },
    { date: "04月", value: 2.9 },
    { date: "05月", value: 6.1 },
    { date: "06月", value: 7.8 },
    { date: "07月", value: 5.6 },
    { date: "08月", value: 10.2 },
    { date: "09月", value: 12.4 },
  ],
  records: [
    {
      code: "688981",
      name: "中芯国际",
      buyDate: "2026-05-12",
      buyPrice: "88.40",
      sellDate: "2026-05-20",
      sellPrice: "94.10",
      position: "12%",
      pnlPercent: "+6.45%",
      buyReason: "半导体板块热度上行，突破平台",
      sellReason: "达到第一止盈区间",
      review: "买点纪律较好，卖点偏保守，可观察二次确认。",
    },
    {
      code: "300750",
      name: "宁德时代",
      buyDate: "2026-05-14",
      buyPrice: "232.00",
      sellDate: "2026-05-22",
      sellPrice: "226.20",
      position: "10%",
      pnlPercent: "-2.50%",
      buyReason: "新能源权重企稳，成交额放大",
      sellReason: "跌破计划止损线",
      review: "板块强度不足，后续需等待排名改善。",
    },
    {
      code: "000977",
      name: "浪潮信息",
      buyDate: "2026-05-17",
      buyPrice: "55.80",
      sellDate: "2026-05-28",
      sellPrice: "61.10",
      position: "15%",
      pnlPercent: "+9.50%",
      buyReason: "算力方向强势，趋势放量",
      sellReason: "高位量能异常放大",
      review: "交易计划完整，出场符合纪律。",
    },
  ],
};

export const dailyReport: DailyReport = {
  date: "2026-05-30",
  conclusion:
    "市场情绪中性偏暖，主线集中在半导体设备与算力基础设施。短线可继续观察强势方向的低吸确认，避免追高和弱势题材反抽。",
  indexPerformance: [
    "上证指数小幅收红，权重稳定但上行动能一般。",
    "深证成指小幅回落，成长风格内部出现分化。",
    "创业板指表现相对更强，新能源与科技权重贡献较多。",
  ],
  sectorOrder: ["半导体设备", "算力基础设施", "低空经济", "机器人", "创新药"],
  watchTargets: [
    {
      code: "688981",
      name: "中芯国际",
      reason: "半导体设备方向热度领先，个股处于趋势修复结构。",
      buyTrigger: "放量突破 94.20，且板块热度维持前三。",
      stopLoss: "跌破 88.60 或板块热度跌出前五。",
      takeProfit: "第一目标 99.80，第二目标 103.50。",
      positionAdvice: "模拟研究仓位不超过 10%。",
      risks: "消息面敏感，高开追涨风险较高。",
    },
    {
      code: "000977",
      name: "浪潮信息",
      reason: "算力主题成交活跃，资金承接仍在。",
      buyTrigger: "突破 59.20 且分时回踩不破均线。",
      stopLoss: "跌破 55.80 或成交量异常萎缩。",
      takeProfit: "第一目标 62.50，第二目标 65.00。",
      positionAdvice: "模拟研究仓位不超过 8%。",
      risks: "主题拥挤度上升，需警惕高位震荡。",
    },
  ],
  previousReview: [
    "宁德时代未触发突破条件，继续观察 240.00 压力位。",
    "中际旭创达到高位分歧区，短线从强观察降为谨慎观察。",
  ],
  avoidDirections: ["地产链", "高位缩量题材", "连续跌破均线的弱周期资源股"],
};

export const routePages = [
  {
    href: "/",
    title: "Dashboard",
    name: "首页总览",
    description: "市场概览、热点板块、量化观察和风险提示。",
  },
  {
    href: "/market",
    title: "Market",
    name: "市场行情",
    description: "指数、市场广度、成交额、涨跌幅榜和情绪评分。",
  },
  {
    href: "/sectors",
    title: "Sectors",
    name: "热点板块",
    description: "板块热度、龙头股、风险等级和轮动方向。",
  },
  {
    href: "/stocks",
    title: "Stocks",
    name: "股票池",
    description: "量化观察股票、评级、触发条件和风控边界。",
  },
  {
    href: "/strategy",
    title: "Strategy",
    name: "策略回测",
    description: "静态策略规则、模拟回测结果和交易明细。",
  },
  {
    href: "/report",
    title: "Report",
    name: "每日投研报告",
    description: "市场结论、观察标的、复盘区域和不碰方向。",
  },
  {
    href: "/journal",
    title: "Journal",
    name: "交易记录",
    description: "交易统计、盈亏曲线、记录表格和复盘提醒。",
  },
  {
    href: "/settings",
    title: "Settings",
    name: "系统设置",
    description: "数据源、风控参数、报告设置和系统说明。",
  },
] as const;

export const riskNotes = [
  "当前数据均为 mock 模拟数据，不代表真实行情。",
  "平台第二阶段仍只用于静态产品原型和研究流程展示。",
  "不接入真实交易接口，不提供自动交易或实盘下单功能。",
  "量化信号只能作为研究线索，不能替代独立判断和风险控制。",
];

export const marketIndices = indexData;
export const marketBreadth = {
  ...marketOverview.breadth,
  turnover: marketOverview.turnover.total,
  riskLevel: marketOverview.riskLevel,
};
export const sectorRanking = sectorRankings;
export const observationStocks = stockWatchlist.map((stock) => ({
  code: stock.code,
  name: stock.name,
  signal: stock.rating,
  reason: stock.buyTrigger,
  risk: stock.risk,
}));
export const flowSeries = intradayMarketFlow;
